apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1 # How many instances of your app
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: image-engine:latest # Replace with your Docker image
        ports:
        - containerPort: 8000 # Port your app listens on
