apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-app # Connects to the Deployment
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 8000 # Port in the container
  type: NodePort # Makes the app accessible via a port on your machine
